---
remove_dirs:

create_dirs:
  - .ssh

remove_packages:

install_packages:
  - ansible
  - apt-transport-https
  - ca-certificates
  - git
  - gnupg
  - htop
  - software-properties-common


# Defaults for ansible
repo: https://github.com/TvanMeer/personal_ansible_configs.git