---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false

  roles:
    - base
    - role: workstation 
      when: ansible_default_ipv4.address in ["192.168.178.2",]

  tasks:
    - name: cleanup package cache
      apt:
        autoclean: true
      changed_when: false

    - name: autoremove orphan packages
      apt:
        autoremove: true
        purge: true