---
# Run update and base role on all hosts
- hosts: all
  become: true
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: yes


# Run base role on all hosts
- hosts: all
  become: true
  roles:
    - base


# Run workstation role on hosts in workstation group
- hosts: workstation
  become: true
  roles:
    - workstation
    

# Update and cleanup packages on all hosts
- hosts: all
  become: true
  post_tasks:
  - name: update repositories again and upgrade packages
    apt: 
      upgrade: dist
      update_cache: yes
  - name: cleanup package cache
    apt:
      autoclean: yes
  - name: autoremove orphan packages
    apt:
      autoremove: yes
      purge: yes