---
# Run update and base role on all hosts
- hosts: all
  become: true
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: yes


# Run base role on all hosts
- hosts: all
  become: true
  roles:
    - base


# Run workstation role on hosts in workstation group
- hosts: workstation
  become: true
  roles:
    - workstation
    

# Cleanup on all hosts
- hosts: all
  become: true
  tasks:
  - name: cleanup package cache
    apt:
      autoclean: yes
  - name: autoremove orphan packages
    apt:
      autoremove: yes
      purge: yes