---

# system setup (workstation)

- name: set folder structure in home directory
  import_tasks: system_setup/directories.yml

- name: configure nautilus file manager
  import_tasks: system_setup/gnome/nautilus.yml

- name: configure desktop interface settings
  import_tasks: system_setup/gnome/interface.yml

- name: set wallpaper
  import_tasks: system_setup/wallpaper.yml

- name: copy ubuntu templates
  import_tasks: system_setup/ubuntu_templates.yml



# software installer (workstation)

- name: install packages through standard package manager
  import_tasks: software/_packages.yml
