---
- name: remove standard directories in home folder
  become_user: tom
  file:
    path: /home/tom/{{ item }}
    state: absent
  with_items:
    - examples.desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: create new home directories
  file:
    path: /home/tom/{{ item.dir }}
    state: directory
    owner: tom
    group: tom
    mode: 0700
  with_items:
    - { dir: Aantekeningen }
    - { dir: Administratie }
    - { dir: Brainstorm }
    - { dir: Cheatsheets }
    - { dir: Code }
    - { dir: Desktop }
    - { dir: Dump }
    - { dir: Github }
    - { dir: Logs }
    - { dir: Studie }
    - { dir: Werk }