---
- name: copy bookmarks settings file for root
  copy:
    src: nautilus/user-dirs.defaults
    dest: /etc/xdg/user-dirs.defaults
    owner: root
    group: root
    mode: 0644

- name: copy bookmarks settings file for user
  become_user: tom
  copy:
    src: nautilus/user-dirs.dirs
    dest: ~/.config/user-dirs.dirs
    owner: tom
    group: tom
    mode: 0600

- name: copy bookmark settings file for gtk 3.0
  become_user: tom
  copy:
    src: nautilus/bookmarks
    dest: ~/.config/gtk-3.0
    owner: tom
    group: tom
    mode: 0664

- name: set dconf settings
  become_user: tom
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: "/org/gnome/nautilus/icon-view/default-zoom-level"
      value: "'small'"
    - key: "/org/gnome/nautilus/list-view/default-visible-columns"
      value: "['name', 'size', 'date_modified']"
    - key: "/org/gnome/nautilus/list-view/use-tree-view"
      value: "true"
    - key: "/org/gnome/nautilus/preferences/click-policy"
      value: "'single'"
    - key: "/org/gnome/nautilus/preferences/default-folder-viewer"
      value: "'icon-view'"
    - key: "/org/gnome/nautilus/preferences/show-hidden-files"
      value: "true"
    - key: "/org/gnome/nautilus/window-state/initial-size"
      value: "(1237, 873)"