---
- name: remove unwanted packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items: "{{ remove_packages }}"


- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ install_packages }}"


- name: install vscodium
  import_tasks: vscodium.yml