---
- name: remove unwanted packages
  package:
    force_apt_get: yes
    state: absent
    purge: yes
    name:
      # show all with 'apt list --installed'
      - wbrazilian
      - wbritish
      - wfrench
      - witalian
      - wngerman
      - wogerman
      - wportuguese
      - wspanish
      - wswiss
      - xbrlapi

- name: install dependencies
  apt:
    name:
      - gnome-keyring
    state: latest


- name: install curl
  import_tasks: curl.yml

- name: install vscodium
  import_tasks: vscodium.yml