---
- name: add vscodium gpg key
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present

- name: add vscodium repository
  apt_repository:
    repo: deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main
    state: present
    update_cache: true

- name: install vscodium
  apt:
    name: codium
    state: latest
    update_cache: yes

- name: configure marketplace api endpoints
  become_user: tom
  copy:
    src: vscodium/product.json
    dest: ~/.config/VSCodium
    mode: 0700