---
- name: add vscodium gpg key
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present

- name: add vscodium repository
  apt_repository:
    repo: deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main
    state: present
    update_cache: true

- name: install vscodium
  apt:
    name: codium
    state: latest
    update_cache: yes

- name: copy configuration files
  become_user: tom
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0700
  with_items:
    - src: vscodium/product.json
      dest: ~/.config/VSCodium
    - src: vscodium/settings.json
      dest: ~/.config/VSCodium/User
    - src: vscodium/keybindings.json
      dest: ~/.config/VSCodium/User

- name: get list of installed extensions
  become_user: tom
  shell: codium --list-extensions
  register: extensions_list
  changed_when: false

- name: install plugins
  become_user: tom
  shell: "codium --install-extension {{ item }}"
  with_items:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
  when: item not in extensions_list.stdout_lines
