---
- name: add vscodium apt key
  ansible.builtin.apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present

- name: install vscodium
  apt:
    name: codium
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]