---
- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: latest
    autoclean: true

- name: install apt apps
  apt:
    name:
      - htop
    state: latest