---
- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/20"
    job: "/usr/bin/ansible-pull -o -U https://github.com/TvanMeer/personal_ansible_configs.git > /dev/null"