---
- name: create new home directories
  file:
    path: /home/tom/{{ item }}
    state: directory
    owner: tom
    group: tom
    mode: 0700
  with_items: "{{ create_dirs }}"


- name: set Logs folder permissions
  file:
    path: /home/tom/Logs
    state: directory
    owner: tom
    group: root
    mode: 0420


- name: create vault keyfile
  file:
    path: /home/ansible/.vaultkey
    owner: ansible
    group: root
    mode: 0400