---
- name: create new home directories
  file:
    path: /home/tom/{{ item }}
    state: directory
    owner: tom
    group: tom
    mode: 0700
  with_items: "{{ create_dirs }}"

- name: create vault keyfile
  file:
    path: /home/tom/.geheim/ansible_vault_key
    owner: tom
    group: tom
    mode: 0600