---
- name: create new home directories
  file:
    path: /home/tom/{{ item }}
    state: directory
    owner: tom
    group: tom
    mode: 0700
  with_items: "{{ create_dirs }}"

- name: create vault keyfile
  file:
    path: /home/ansible/.vaultkey
    owner: ansible
    group: root
    mode: 0400