---
- name: set ownership of ansible.log to user ansible
  file:
    path: /var/log/ansible.log
    owner: ansible
    group: root
    mode: 0644

- name: create ansible-pull logfile
  copy:
    content: ""
    dest: /var/log/ansible_pull.log
    force: no
    owner: ansible
    group: root
    mode: 0644

- name: create symlinks in logs directory
  file:
    src: '{{ item.key }}'
    dest: '/home/tom/Logs/{{ item.value }}'
    state: link
  loop: "{{ lookup('ansible.builtin.dict', log_symlinks) }}"
