---
- name: allow all connections by default and enable ufw
  ufw:
    state: enabled
    direction: outgoing
    policy: allow


- name: deny incoming requests
  ufw:
    state: enabled
    direction: incoming
    policy: deny


- name: create logfile
  file:
    path: /var/log/ufw.log
    owner: syslog
    group: adm
    mode: '0640'


- name: switch on logging, default level low
  ufw:
    logging: 'on'
